server:
  host: "0.0.0.0"
  port: "8080"
  base_url: "/api/v1"
  read_timeout: "5s"
  write_timeout: "5s"
  idle_timeout: "5s"
  min_username_length: 3

tracer:
  service_name: "message-service"
  sampler_type: "const"
  sampler_param: 1
  reporter_log_spans: true
  reporter_buffer_flush_interval: "1s"
  reporter_host: "jaeger"
  reporter_port: "6831"
  collector_endpoint: ""
  disable: false

lts:
  master:
    host: "host.docker.internal"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "internation_site"
    sslmode: "disable"
    pool:
      max_open_conns: 200
      max_idle_conns: 10
      conn_max_lifetime: "5m"

logger:
  level: "debug"
  stdout: true
  stacktrace: false
  file:
    enabled: false
    path: "/var/log/p2p-service.log"
